=== SolidShen/trojai_round12_weight_analysis/metaparameters_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Trojan Detection Container (trojai-example) - Perspecta-PurdueRutgers v2.1",
  "technique": "Weight Production Feature GradientBoosting Classifier",
  "technique_description": "Take weight production as features with normalization, train a GB classifier",
  "technique_changes": "initial commit",
  "commit_id": "8b5de2e6f45b06d6a380b3c91fd9b267651792ce",
  "repo_name": "git@github.com:SolidShen/trojai_round12_weight_analysis.git",
  "required": [],
  "additionalProperties": false,
  "type": "object",
  "properties": {
	
	
	"train_weight_feat_param_if_bias": {
		"description": "If bias is added to the weight feature",
		"type": "boolean"
	},



	"train_gradient_boosting_param_n_estimators": {
		"description": "Number of estimators in the classifier.",
		"type": "integer",
		"minimum": 1,
		"maximum": 8000,
		"suggested_minimum": 1000,
		"suggested_maximum": 5000
	},


	"train_gradient_boosting_param_learning_rate": {
		"description": "Learning rate",
		"type": "number",
		"minimum": 0.0,
		"maximum": 1.0,
		"suggested_minimum": 0.0,
		"suggested_maximum": 1e-2
	},

	"train_gradient_boosting_param_max_depth": {
		"description": "The maximum depth of the tree",
		"type": "integer",
		"minimum": 1,
		"maximum": 20,
		"suggested_minimum": 1,
		"suggested_maximum": 20
	},

	"train_gradient_boosting_param_subsample": {
		"description": "The minimum number of samples required to split an internal node.",
		"type": "number",
		"minimum": 0,
		"maximum": 5,
		"suggested_minimum": 0,
		"suggested_maximum": 2
	},

	"train_gradient_boosting_param_max_features": {
		"description": "The number of features to consider when looking for the best split.",
		"type": "string",
		"enum": ["sqrt"]
	},

	"train_gradient_boosting_param_loss": {
		"description": "The loss function to be optimized.",
		"type": "string",
		"enum": ["log_loss"]
	}


  }
}

=== SolidShen/trojai_round12_weight_analysis/learned_parameters/metaparameters.json
{"train_weight_feat_param_if_bias": true, "train_gradient_boosting_param_n_estimators": 4000, "train_gradient_boosting_param_learning_rate": 0.001, "train_gradient_boosting_param_max_depth": 3, "train_gradient_boosting_param_subsample": 0.7, "train_gradient_boosting_param_max_features": "sqrt", "train_gradient_boosting_param_loss": "log_loss"}
